version: 0.2
        
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing ===== cfn-lint =====
      - pip3 install cfn-lint  
    
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo verifying python version installed
      - python3 --version
      - ls -l
      - echo === Verifying cfn-lint installation ====
      - cfn-lint --version
    finally:
      - echo moving to build stage
    
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo I WILL CHECK IF THE CLOUDFORMATION TEMPLATE
      - ls -l
      - echo === RUN CFN-LINT ====
      - cfn-lint pipeline.yml
      - echo ==== BUILD OUR TEMPLATE ====
      - aws cloudformation package --template-file pipeline.yml --s3-bucket testing-bckt --output-template-file build-artifact-template.yml
    finally:
      - echo build stage ended
    
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
    finally:
      - echo post_build stage ended
artifacts:
  files:
    - build-artifact-template.yml
   
