version: 0.2
        
phases:
  install:
    runtime-versions:
      python: 3.9
    
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo verifying python version installed
      - python3 --version
      - ls -l
    finally:
      - echo moving to build stage
    
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo build stage ended
    
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
    finally:
      - echo post_build stage ended
artifacts:
  files:
    - "**/*" # Collects all files in the project directory
   
